[0m[[0mdebug[0m] [0mExecuting docker push nexus.***REMOVED***.test/***REMOVED***-catalog-manager:1.0.4-SNAPSHOT[0m
[0m[[0minfo[0m] [0mThe push refers to a repository [nexus.***REMOVED***.test/***REMOVED***-catalog-manager][0m
[0m[[31merror[0m] [0mGet ***REMOVED***://nexus.***REMOVED***.test/v2/: x509: certificate is valid for *.***REMOVED***.***REMOVED***.it, ***REMOVED***.***REMOVED***.it, not nexus.***REMOVED***.test[0m
java.lang.RuntimeException: Nonzero exit value: 1
	at scala.sys.package$.error(package.scala:27)
	at com.typesafe.sbt.packager.docker.DockerPlugin$.publishDocker(DockerPlugin.scala:336)
	at com.typesafe.sbt.packager.docker.DockerPlugin$$anonfun$projectSettings$20.apply(DockerPlugin.scala:125)
	at com.typesafe.sbt.packager.docker.DockerPlugin$$anonfun$projectSettings$20.apply(DockerPlugin.scala:121)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[0m[[31merror[0m] [0m(root/docker:[31mpublish[0m) Nonzero exit value: 1[0m
